"""Generate the human-readable markdown from the canonical JSON.

The render is a projection, never a source. `slicer check` re-renders into
memory and compares bytes, so this module must be deterministic: no
timestamps, no versions, no hostnames, no unordered iteration.
"""

from __future__ import annotations

import html
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Mapping

from slicer import ids
from slicer.config import Config
from slicer.errors import RenderError
from slicer.model import Index, Item, Slice

BANNER_PREFIX = "<!-- GENERATED by slicer."
ROADMAP_NAME = "ROADMAP.md"
ROADMAP_HTML_NAME = "ROADMAP.html"
SLICES_SUBDIR = "slices"

EMDASH = "—"
MIDDOT = "·"

PLACEHOLDER_RE = re.compile(r"\{\{\s*(\w+)\s*\}\}")


def expand(template: str, ctx: Mapping[str, str]) -> str:
  """Substitute `{{key}}`. No loops, no conditionals, no eval.

  Repetition is flattened in Python before it reaches a template, so that
  whitespace logic stays testable rather than living in template syntax.
  """

  def replace(m: re.Match[str]) -> str:
    key = m.group(1)
    if key not in ctx:
      raise RenderError(f"template uses {{{{{key}}}}}, which is not a known placeholder")
    return ctx[key]

  return PLACEHOLDER_RE.sub(replace, template)


def tidy(text: str) -> str:
  """Collapse the gaps left by empty placeholders and fix the file ending.

  Templates are written for the full case; an absent optional block would
  otherwise leave a run of blank lines that differs per slice.
  """
  text = "\n".join(line.rstrip() for line in text.split("\n"))
  text = re.sub(r"\n{3,}", "\n\n", text)
  return text.strip("\n") + "\n"


def banner(source: str) -> str:
  return (
    f"{BANNER_PREFIX} Source: {source}. "
    "Run `slicer render` after editing; `slicer check` fails if this file is stale. "
    "Do not edit. -->"
  )


def slice_header(sl: Slice, cfg: Config, item_notes: "list[str]" = ()) -> str:
  """The lead blocks, the bold metadata line, and any `Depends on` line."""
  flags = "".join(f" `[{f}]`" for f in sl.flags)
  treekey = "Trees" if sl.trees_plural else "Tree"
  meta = (
    f"**Findings:** {sl.findings_note} {MIDDOT} **Size: {sl.size}**{flags} "
    f"{MIDDOT} **{treekey}:** {sl.trees_note}"
  )
  blocks = list(sl.lead) + [meta]
  if sl.depends_note:
    blocks[-1] = blocks[-1] + "\n" + sl.depends_note
  blocks.extend(sl.notes)       # legacy/migrate notes carried on the slice
  blocks.extend(item_notes)     # notes added with `slicer note` (on the item)
  blocks.append(sl.boundary)
  return "\n\n".join(b for b in blocks if b)


def render_slice(sl: Slice, cfg: Config, template: str, item_notes: "list[str]" = ()) -> bytes:
  sections = "\n\n".join(
    f"## {s.heading}\n\n{s.body}" if s.body else f"## {s.heading}" for s in sl.sections
  )
  body = expand(
    template,
    {
      "id": sl.id,
      "title": sl.title,
      "emdash": EMDASH,
      "middot": MIDDOT,
      "header": slice_header(sl, cfg, item_notes),
      "sections": sections,
    },
  )
  source = f".slicer/slices/{sl.id}.json"
  return (banner(source) + "\n\n" + tidy(body)).encode("utf-8")


def cell(text: str) -> str:
  """Make a value safe to put in a markdown table cell.

  A pipe would split the cell it sits in and a newline would end the table
  early, so both have to go. Escaping happens here rather than on the way in,
  for two reasons: a status label comes from config and never passes through
  input validation at all, and storing an escaped value would break the
  byte-identity round trip `migrate` depends on.
  """
  return " ".join(text.split()).replace("|", "\\|")


def _id_cell(item: Item) -> str:
  link = f"[{item.id}]({SLICES_SUBDIR}/{item.id}.md)" if item.has_slice else item.id
  return cell(link)


def render_row(item: Item, position: int, cfg: Config, template: str) -> str:
  size = item.size + "".join(f" `[{f}]`" for f in item.flags)
  # A retired row still renders, so the reason it was retired has to be on it;
  # the status column alone does not tell a reader why. Join what is present
  # rather than stripping afterwards: `.strip(" ·")` took a character *set*,
  # so it ate a middot the user had written at either end of their findings.
  findings = f" {MIDDOT} ".join(p for p in (item.findings, item.reason) if p)
  # An item stored before titles were validated may have none. Say so, rather
  # than rendering a blank cell nobody can act on.
  title = cell(item.display_title()) or f"(untitled {item.id})"
  return expand(
    template,
    {
      "position": str(position),
      "idcell": _id_cell(item),
      "id": cell(item.id),
      "title": title,
      "size": cell(size),
      "effort": "-" if item.effort is None else str(item.effort),
      "trees": cell(", ".join(item.trees)),
      "findings": cell(findings),
      "status": cell(cfg.status_label(item.status)),
    },
  ).strip("\n")


# An escaped pipe is content, not a cell wall, so it must not be counted.
UNESCAPED_PIPE_RE = re.compile(r"(?<!\\)\|")


def _cells(row: str) -> int:
  return len(UNESCAPED_PIPE_RE.findall(row)) - 1


def _check_row(row: str, header: str) -> None:
  """A generated row must have as many cells as its own table's header.

  Never expected to fire: every value goes through `cell` first. It is here to
  catch the next cell someone adds without doing that, and a `row.md` edited
  to an arity the header does not share.
  """
  got, want = _cells(row), _cells(header)
  if got != want:
    raise RenderError(f"generated table row has {got} cells, header has {want}: {row}")


def render_roadmap(index: Index, cfg: Config, template: str, row_template: str) -> bytes:
  # Effort is a placeholder a template may adopt. One that never names it keeps
  # the previous seven columns, so an existing row.md still renders.
  has_effort = bool(re.search(r"\{\{\s*effort\s*\}\}", row_template))
  if has_effort:
    header = "| # | Slice | Title | Size | Effort | Trees | Findings | Status |"
    sep = "|---|---|---|---|---|---|---|---|"
    group_gap = "| | | | | | | |"
  else:
    header = "| # | Slice | Title | Size | Trees | Findings | Status |"
    sep = "|---|---|---|---|---|---|---|"
    group_gap = "| | | | | | |"
  ordered_keys = index.pass_keys()

  chunks: list[str] = []
  position = 0
  for key in ordered_keys:
    info = index.pass_info(key)
    members = [it for it in index.items if it.pass_key == key]
    lines: list[str] = []
    if info is not None and info.heading:
      lines.append(info.heading)
    elif key:
      lines.append(f"## {key}")
    if info is not None and info.intro:
      lines.append(info.intro)
    rows: list[str] = []
    group = ""
    for item in members:
      position += 1
      if item.group and item.group != group:
        group = item.group
        rows.append(f"| {cell(group)} {group_gap}")
      rows.append(render_row(item, position, cfg, row_template))
    for row in rows:
      _check_row(row, header)
    lines.append("\n".join([header, sep, *rows]))
    if info is not None and info.outro:
      lines.append(info.outro)
    chunks.append("\n\n".join(lines))

  tally = {label: 0 for label in cfg.statuses.values()}
  for item in index.items:
    tally[cfg.status_label(item.status)] = tally.get(cfg.status_label(item.status), 0) + 1
  summary = f"{len(index.items)} items " + MIDDOT + " " + (" " + MIDDOT + " ").join(
    f"{label} {count}" for label, count in tally.items() if count
  )

  body = expand(
    template,
    {
      "preamble": index.preamble,
      "goals": _titled("Goals", index.goals),
      "non_goals": _titled("Non-goals", index.non_goals),
      "summary": summary,
      "groups": "\n\n---\n\n".join(chunks),
      "epilogue": index.epilogue,
    },
  )
  return (banner(".slicer/index.json") + "\n\n" + tidy(body)).encode("utf-8")


def _titled(title: str, text: str) -> str:
  """A `## title` block, or nothing when empty so `tidy` collapses the gap."""
  return f"## {title}\n\n{text}" if text.strip() else ""


_HTML_STYLE = """\
  :root { color-scheme: light dark; }
  body { font-family: system-ui, sans-serif; max-width: 64rem; margin: 2rem auto;
         padding: 0 1rem; line-height: 1.5; }
  h1 { border-bottom: 2px solid currentColor; padding-bottom: .2rem; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
  th, td { text-align: left; padding: .3rem .5rem; border-bottom: 1px solid #8884;
           vertical-align: top; }
  .summary { opacity: .75; }
  .prose { opacity: .9; }
  tr.done { opacity: .55; }
  td.status { font-weight: 600; }
  tr.started td.status { color: #1a7f37; }
  tr.parked td.status, tr.retired td.status { color: #9a6700; }
  @media (prefers-color-scheme: dark) {
    th, td { border-bottom-color: #8886; }
    tr.started td.status { color: #3fb950; }
    tr.parked td.status, tr.retired td.status { color: #d29922; }
  }
"""


def _status_class(status: str, cfg: Config) -> str:
  """A CSS class per status, keyed off the config's role pointers."""
  return {
    cfg.open_status: "open", cfg.started_status: "started", cfg.done_status: "done",
    cfg.parked_status: "parked", cfg.retired_status: "retired",
  }.get(status, "other")


def _prose_html(text: str) -> str:
  """Prose blocks as escaped paragraphs. Not a markdown renderer: blank lines
  start paragraphs and single newlines become line breaks; nothing else."""
  blocks = [b.strip() for b in text.split("\n\n") if b.strip()]
  return "\n".join("<p>" + html.escape(b).replace("\n", "<br>\n") + "</p>" for b in blocks)


def render_html(index: Index, cfg: Config) -> bytes:
  """A standalone, styled HTML view of the roadmap. Deterministic, escaped,
  stdlib-only; a browser-readable projection beside ROADMAP.md."""
  e = html.escape
  parts = [
    banner(".slicer/index.json"),
    '<!DOCTYPE html>',
    '<html lang="en"><head><meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    "<title>Roadmap</title>",
    f"<style>\n{_HTML_STYLE}</style>",
    "</head><body>",
    "<h1>Roadmap</h1>",
  ]
  if index.preamble.strip():
    parts.append(f'<div class="prose">{_prose_html(index.preamble)}</div>')
  for title, text in (("Goals", index.goals), ("Non-goals", index.non_goals)):
    if text.strip():
      parts.append(f'<section><h2>{e(title)}</h2><div class="prose">{_prose_html(text)}</div></section>')

  tally = {label: 0 for label in cfg.statuses.values()}
  for item in index.items:
    tally[cfg.status_label(item.status)] = tally.get(cfg.status_label(item.status), 0) + 1
  summary = f"{len(index.items)} items " + MIDDOT + " " + (" " + MIDDOT + " ").join(
    f"{e(label)} {count}" for label, count in tally.items() if count
  )
  parts.append(f'<p class="summary">{summary}</p>')

  position = 0
  for key in index.pass_keys():
    info = index.pass_info(key)
    members = [it for it in index.items if it.pass_key == key]
    if info is not None and info.heading:
      parts.append(f"<h2>{e(info.heading)}</h2>")
    elif key:
      parts.append(f"<h2>{e(key)}</h2>")
    if info is not None and info.intro:
      parts.append(f'<div class="prose">{_prose_html(info.intro)}</div>')
    parts.append(
      "<table><thead><tr><th>#</th><th>ID</th><th>Title</th><th>Size</th>"
      "<th>Effort</th><th>Trees</th><th>Findings</th><th>Status</th></tr></thead><tbody>"
    )
    group = ""
    for item in members:
      position += 1
      if item.group and item.group != group:
        group = item.group
        parts.append(f'<tr class="group"><td></td><td colspan="7"><strong>{e(group)}</strong></td></tr>')
      size = item.size + "".join(f" [{f}]" for f in item.flags)
      findings = f" {MIDDOT} ".join(p for p in (item.findings, item.reason) if p)
      title = item.display_title() or f"(untitled {item.id})"
      parts.append(
        f'<tr class="{_status_class(item.status, cfg)}"><td>{position}</td>'
        f"<td>{e(item.id)}</td><td>{e(title)}</td><td>{e(size)}</td>"
        f"<td>{'-' if item.effort is None else item.effort}</td>"
        f'<td>{e(", ".join(item.trees))}</td><td>{e(findings)}</td>'
        f'<td class="status">{e(cfg.status_label(item.status))}</td></tr>'
      )
    parts.append("</tbody></table>")
    if info is not None and info.outro:
      parts.append(f'<div class="prose">{_prose_html(info.outro)}</div>')

  if index.epilogue.strip():
    parts.append(f'<div class="prose">{_prose_html(index.epilogue)}</div>')
  parts.append("</body></html>")
  return ("\n".join(parts) + "\n").encode("utf-8")


@dataclass
class RenderDiff:
  missing: list[str] = field(default_factory=list)
  differing: list[str] = field(default_factory=list)
  orphans: list[str] = field(default_factory=list)
  kept: list[str] = field(default_factory=list)

  @property
  def stale(self) -> bool:
    return bool(self.missing or self.differing or self.orphans)


def plan(state) -> dict[str, bytes]:
  """The full expected contents of `.slicer/render/`, keyed by relative path."""
  cfg = state.config
  out: dict[str, bytes] = {
    ROADMAP_NAME: render_roadmap(
      state.index, cfg, state.template("roadmap.md"), state.template("row.md")
    ),
    ROADMAP_HTML_NAME: render_html(state.index, cfg),
  }
  slice_template = state.template("slice.md")
  for item in state.index.items:
    sl = state.slices.get(item.id)
    if sl is None:
      continue
    # render.write joins this onto the render root and mkdirs, so a bad id
    # escapes here as surely as it does in the slices directory.
    ids.require_valid(item.id)
    out[f"{SLICES_SUBDIR}/{item.id}.md"] = render_slice(sl, cfg, slice_template, item.notes)
  return out


def compare(expected: Mapping[str, bytes], root: Path) -> RenderDiff:
  diff = RenderDiff()
  for rel, want in sorted(expected.items()):
    path = root / rel
    if not path.is_file():
      diff.missing.append(rel)
    elif path.read_bytes() != want:
      diff.differing.append(rel)
  if root.is_dir():
    generated = sorted(p for pat in ("*.md", "*.html") for p in root.rglob(pat))
    for path in generated:
      rel = path.relative_to(root).as_posix()
      if rel in expected:
        continue
      head = path.read_text(encoding="utf-8", errors="replace").split("\n", 1)[0]
      (diff.orphans if head.startswith(BANNER_PREFIX) else diff.kept).append(rel)
  return diff


def write(expected: Mapping[str, bytes], root: Path, diff: RenderDiff) -> list[str]:
  """Write only what changed, and remove only files slicer itself generated."""
  touched: list[str] = []
  for rel in sorted(set(diff.missing) | set(diff.differing)):
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(expected[rel])
    touched.append(rel)
  for rel in diff.orphans:
    (root / rel).unlink()
    touched.append(rel)
  return touched


def write_atomic(expected: Mapping[str, bytes], root: Path, diff: RenderDiff) -> list[str]:
  """Like `write`, but leave `root` byte-for-byte unchanged if any write fails.

  `write` replaces and deletes generated files one at a time, so a failure partway
  leaves `.slicer/render/` matching neither the old state nor the new one. Snapshot
  every file this write would replace or delete -- and note the ones that do not
  exist yet -- run the write, and on failure restore the snapshot before re-raising.
  An `OSError` becomes a `RenderError` so a render-gated mutation whose render cannot
  be written exits 2 (render), the same as one whose render cannot be planned, rather
  than 3 (io). This is what lets a render-first mutation roll back as a whole.
  """
  saved: dict[str, bytes] = {}
  created: list[str] = []
  for rel in sorted(set(diff.missing) | set(diff.differing) | set(diff.orphans)):
    path = root / rel
    if path.is_file():
      saved[rel] = path.read_bytes()
    else:
      created.append(rel)  # a file the write creates; a rollback deletes it
  try:
    return write(expected, root, diff)
  except OSError as exc:
    _restore(root, saved, created)
    raise RenderError(f"could not write render output, left it unchanged: {exc}") from exc
  except BaseException:
    _restore(root, saved, created)
    raise


def _restore(root: Path, saved: Mapping[str, bytes], created: list[str]) -> None:
  """Undo a failed `write_atomic`: rewrite the bytes it replaced or deleted, and
  delete the files it had newly created."""
  for rel, data in saved.items():
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
  for rel in created:
    path = root / rel
    if path.is_file():
      path.unlink()


def unified(expected: Mapping[str, bytes], root: Path, rel: str, limit: int = 30) -> str:
  import difflib

  want = expected[rel].decode("utf-8").splitlines()
  got = (root / rel).read_text(encoding="utf-8").splitlines() if (root / rel).is_file() else []
  lines = list(difflib.unified_diff(got, want, f"{rel} (on disk)", f"{rel} (expected)", lineterm=""))
  return "\n".join(lines[:limit])
